import "./globals.css";
import localFont from 'next/font/local'

const defaultFont = localFont({
  src: [
    {
      path: './fonts/gg-sans-Regular.ttf',
      weight: '400'
    },
    {
      path: './fonts/gg-sans-Medium.ttf',
      weight: '500'
    },
    {
      path: './fonts/gg-sans-Semibold.ttf',
      weight: '600'
    },
    {
      path: './fonts/gg-sans-Bold.ttf',
      weight: '700'
    }
  ]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={defaultFont.className}>
      <body>{children}</body>
    </html>
  );
}
